### ISSUE TITLE
Responsive adjustments for small screens

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#104]
Reduce margin on left side. Can the horizontal line under the main nav always line up with the right side of the table?
![Screenshot 2023-03-29 at 12 52 45 PM](https://user-images.githubusercontent.com/158175/228652805-acc38e76-655f-482a-8582-818784ff6466.png)

On X-Small screen, a quick fix for the nav might be to hide the labels and just show icons. Maybe put the counts underneath the icons, or hide them as well. 
![Screenshot 2023-03-29 at 12 58 32 PM](https://user-images.githubusercontent.com/158175/228653903-d3e7494d-c35f-4cf1-bac4-a996b8b69feb.png)

**Comment by annavik** [comment]
Fixed an released!
