### ISSUE TITLE
Update the interface for the captures timeline in session detail view

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#198]
I received some feedback about the timeline interface when giving one demo. It's not clear what the green bars represent and there is enough extra space on the left & right that it feels like something isn't loading. Andre has some updated designs that help clarify the time scale. However perhaps it needs a little more discussion, or experimentation!

**Comment by annavik** [comment]
**Latest design sketch:**
<img width="473" alt="Screenshot 2023-08-22 at 11 09 09" src="https://github.com/RolnickLab/ami-platform/assets/11680517/c7fcfd30-49da-42b4-828d-b4dc312d7e5e">

**Summary of changes to be made:**
- Implement time-spaced version
- Update capture item layout
- Add occurrence count to capture item
- Update detection bar:
    - Gray bar for total number of detections
    - Green bar for detections > threshold
    - Look into detection bar size (scale based on min and max for deployment or even project?)
