### ISSUE TITLE
Offset for session view is incorrect

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#206]
If we try to link to a specific capture in a session (https://api.dev.insectai.org/api/v2/events/1/?capture=1), we get "capture_page_offset" set to 5824 in the response, which seems wrong. So linking to a specific capture is not working properly atm! :)

**Comment by annavik** [comment]
I have noticed many of the early captures (like here) have the offset issue. Not sure if it holds for all, but maybe a clue?

<img width="1596" alt="Screenshot 2023-08-22 at 11 39 30" src="https://github.com/RolnickLab/ami-platform/assets/11680517/d1b7ec47-bb97-4f15-b0e0-8301330e5690">

**Comment by mihow** [comment]
It turns out the offset is okay! The source images for this deployment were totally out-of-wack. I fixed the data and the links between occurrences & sessions are working again!
