### ISSUE TITLE
Add threshold control

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#208]
Based on this setting, we want to control what detections to show in the playback frame. Also, we need this for #198. This is the control:

<img width="1430" alt="Screenshot 2023-08-22 at 11 20 39" src="https://github.com/RolnickLab/ami-platform/assets/11680517/59c02743-b976-4121-a8a6-233fd22c06c6">

**Comment by mihow** [comment]
Some more details:
- The threshold slider should update the visible bounding boxes on the capture image
- It should update without making another request to the backend (the API should have all bboxes with their score)
- It should be sticky, so stay with the session. Perhaps we even save it to the user settings per project?

**Comment by annavik** [comment]
Major parts fixed in https://github.com/RolnickLab/ami-platform/pull/286, will handle remaining parts as separate tasks.
