### ISSUE TITLE
Add project filters

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#212]
When we fetch a group of items, we sometimes want to filter based on project id. Deployments and jobs endpoints have this filter, I could need a similar one for:
- /status/summary
- /occurrences
- /events
- /species

Deployments example: https://api.dev.insectai.org/api/v2/deployments?project=2

**Comment by mihow** [comment]
Thanks for finding these! I added the filter to `/status/summary/?project=2` but will come back to the others.

**Comment by mihow** [comment]
These endpoints can now be filtered by project:
- /occurrences
- /events
- /status/summary

each species can belong to multiple projects, so that filter is slightly different. coming soon.
