### ISSUE TITLE
Create React App -> Vite

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#254]
CRA is no longer the recommended way to setup a React app. See https://github.com/reactjs/react.dev/pull/5487

I think we should migrate to [Vite](https://vitejs.dev/) when we get a chance. It's more performant (faster build times, etc.) and has some other advantages as well. As the FE app gets larger, I think this could be nice.

**Comment by mihow** [comment]
Looks cool! I was wondering what was going to come after "Create React App"
