### ISSUE TITLE
URL params for pagination

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#289]
Pagination works on the sessions list view and other tables. However there is no way to link to a specific page, or jump to a page farther down the line. 

Can we add URL params for pagination on table/gallery list views?

It can mirror the limit & offset params used for the API request to keep things simple. 

https://app.preview.insectai.org/api/v2/events/?project=16&limit=20&offset=0
https://app.preview.insectai.org/projects/16/sessions?limit=20&offset=0

Also if there is a way to jump to the last page, that would be very helpful as often that's where the most moth action is.

**Comment by annavik** [comment]
Good idea!

Also I know Andre has thoughts on more refined navigation here:
<img width="671" alt="Screenshot 2023-10-24 at 21 52 19" src="https://github.com/RolnickLab/ami-platform/assets/11680517/20af559f-b9d9-413a-8257-3cc59b38e8c4">

I still like this, just haven't got to it. Do you think it's a good idea to include this as part of this task? If so, perhaps we should tweak URL params "?limit=20&offset=0" -> "?pageSize=20&page=1" to make them better with UI (we can still keep BE calls the same).

**Comment by mihow** [comment]
Thanks for finding those designs! I think the page & page size params are just fine. I can switch the backend to use pages as well if that's helpful. It's a pre-existing option I can choose from. But let's stick with "snake_case" for url params :)
