### ISSUE TITLE
New view for source image collections

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#297]
### Summary

- Need way to view collections of source images directly as a gallery / table view 
- API endpoints exist now
- Collections are project-wide & can contain captures from any deployment or session within the project
- Doesn't need a link from the main tab menu (yet). We can link to it from the job detail panel.
- Could have an index view? But optional for now. 
- Breadcrumbs can be Project -> Collections -> Collection name

### Endpoint for collection data
https://api.dev.insectai.org/api/v2/captures/?collections=1

### Optional index view endpoint
https://api.dev.insectai.org/api/v2/captures/collections/

### Table view columns
Thumbnail, Deployment, Session/Event, Detections count, Occurrence count, Job, Last processed 

Link thumbnail and session/event cells to capture detail within Session view.

### Columns for optional index page table
Collection name, Sampling method, Captures (source_image_count), Created at, Updated at

Link to collection detail gallery

### Some examples of collections

Collections are needed for job processing, exporting tasks to label studio and for running tests on subsets. But also could be helpful for users to view capture highlights or exporting subsets of images.

- Random sample & Other sampling methods (last image from each session)
- Capture favorites
- Test set
- Manually uploaded images

**Comment by annavik** [comment]
Can we add the following info to each capture here? https://api.dev.insectai.org/api/v2/captures/?collections=1
- deployment
  - id
  - name
- event
  - id
  - name
- occurrences_count

So I can add the columns needed :) Info about jobs, maybe for later?

@mihow
