### ISSUE TITLE
Update frontend packages

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#311]
It looks like there are a number of FE packages that have critical vulnerabilities. @annavik can you update these?

https://github.com/RolnickLab/ami-platform/security/dependabot

**Comment by annavik** [comment]
Done! ✅

Most got fixed in CRA->Vite PR (https://github.com/RolnickLab/ami-platform/pull/316). Remaining ones could be resolved automatically except for one annoying case that required some special handling (https://github.com/RolnickLab/ami-platform/pull/322).
