### ISSUE TITLE
Make list view thumbnails clickable

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#313]
Just about every time I view a table that has an image thumbnail as the first item in the row -- I want to click on it! Can we or should we trigger the details modal or view when an image is clicked, even if it has the carousel arrows?

<img width="549" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/b0b78d0d-46fc-49a7-918b-30a81d4e9d47">

**Comment by annavik** [comment]
Yes me too 🫣 I think it's a great idea to at least make something happen!

Showing details would be a quick fix, having a carousel full screen mode would require a bit more work and designs. What do you suggest?

**Comment by mihow** [comment]
I think we cand leave carousel as-is, and only link the image the details modal or view.
