### ISSUE TITLE
Add GDPR / cookie acceptance modal

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#350]
See discussion in https://github.com/RolnickLab/ami-platform/pull/338

**Comment by joseepoirier** [comment]
@annavik How can I help here?

**Comment by annavik** [comment]
Sorry I just assigned you, I planned to write a comment 😅 I think defining the content and logic for this task is a privacy policy matter. I wonder if we could get some help defining this?

**Questions:**
- What should the cookie consent popup say?
- What options should we present in the cookie consent popup ("allow all", "allow necessary", etc.)?
- What effect should the different cookie consent options have on tracking and other cookies?
- Do we need to define a privacy policy?

**Comment by joseepoirier** [comment]
Contacted Mila's Legal/Compliance team for support.
