### ISSUE TITLE
Support sort parameters in URL

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#371]
When clicking on the column headers in a list view, the sort parameter should be added as a param to the URL.

The filter params are already added to the URL when viewing a filtered list view (occurrences for one species)
https://app.preview.insectai.org/projects/24/occurrences?deployment=74

The sort params are already sent as URL params to the API 
https://app.preview.insectai.org/api/v2/occurrences/?project=24&ordering=-updated_at&limit=20&offset=0

While we are at it, the List vs. Gallery tab choices should stick in the URL as well!
https://app.preview.insectai.org/projects/18/occurrences?determination=24
<img width="525" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/97defa53-1ff8-4294-96b7-2d4d0293a9a8">

**Comment by annavik** [comment]
This one is in progress now!

Do you think we should make the summary tab choice part of URL as part of this task as well? If not, I feel sorting as part of URL is not making sense in this specific case (but in all other views!).

<img width="1479" alt="Skärmavbild 2024-06-10 kl  16 19 13" src="https://github.com/RolnickLab/ami-platform/assets/11680517/3032c958-b227-4376-8c51-87321964ce67">

**Comment by mihow** [comment]
Hey yes! That would be so helpful. In every demo, I am clicking back, scrolling down, and clicking the Collections tab repeatidly! Something like /projects/73/collections/ or /projects/73/?section=collections on the project detail page would be awesome. Can you jump to that section of the page as well (to avoid needing to scroll down)?
