### ISSUE TITLE
Make linked numbers more visible 

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#372]
Here are some updated designs from Andre P. to make it more clear that the linked numbers are clickable.

https://www.figma.com/file/wHhSfceHG8Q7sQt1iFnp9x/eB-Desktop-%2B-AMI-Platform?type=design&node-id=829-711&mode=design

![image](https://github.com/RolnickLab/ami-platform/assets/158175/0535b59d-cb90-4a56-9949-222e696d2a51)

**Comment by annavik** [comment]
Fixed in https://github.com/RolnickLab/ami-platform/pull/394
