### ISSUE TITLE
Sign up button should not be visible when logged in

### ISSUE THREAD

**Issue by albags** [RolnickLab/ami-platform#385]
### Description of issue
You can see the "Sign up" button after you logged in.
 

```
Path:      /projects/44
Browser:   Chrome 124.0.0.0 on Windows 10
Viewport:  1920 x 919 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-379--ami-web.netlify.app%2Fprojects%2F44&os=Windows&os_version=10&browser=Chrome&browser_version=124.0&resolution=1920x919&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #379](https://deploy-preview-379--ami-web.netlify.app/projects/44)

**Comment by mVedr** [comment]
Hi, I want to contribute. Are there any guidelines for contribution.

**Comment by annavik** [comment]
> Hi, I want to contribute. Are there any guidelines for contribution.

Hi @mVedr! Happy to hear you want to contribute! 🎉 We are still working on guidelines for external contributions, so probably a bit early... We will keep you updated!
