### ISSUE TITLE
Clarify entity types and terminology in UI

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#399]
After processing some of the user feedback, it seems to be some confusions around the entity types and also the terminology in some cases. For example, what defines a "deployment"? What is a "site"? What does a "collection" include?

To prevent this, I suggest we include some clarifications in the UI here. To not disturb seasoned users with information, I suggest we show this information on demand, for example using tooltips. We could show a short description and also include a link to more detailed information, when we have a wiki?

**Comment by joseepoirier** [comment]
Agree that the terminology causes confusion for users. We started defining some of the terms in the specs + manuals we're writing, but that to me feels like a bandaid that doesn't address the cause. 

Should we consider a 3-step in-app tutorial for the public launch?

**Comment by annavik** [comment]
Here are some quick code sketches I made for a streamlined "entity header" where we can include such clarifications:

![Skärmavbild 2024-06-07 kl  15 02 13](https://github.com/RolnickLab/ami-platform/assets/11680517/405eea38-2435-4d00-878a-0b93bc815373)

![Skärmavbild 2024-06-07 kl  15 02 43](https://github.com/RolnickLab/ami-platform/assets/11680517/7626ed7b-ce6d-42fc-9895-2f5ff8267237)

![Skärmavbild 2024-06-07 kl  15 03 11](https://github.com/RolnickLab/ami-platform/assets/11680517/0df2177f-6941-40c5-81b5-4126a75666a0)

**Comment by annavik** [comment]
Also this header can be place for other "entity actions",  create? Andre can probably refine this a bit though!

**Comment by annavik** [comment]
> Agree that the terminology causes confusion for users. We started defining some of the terms in the specs + manuals we're writing, but that to me feels like a bandaid that doesn't address the cause.
> 
> Should we consider a 3-step in-app tutorial for the public launch?

Yes I agree just explanations is probably not enough in some cases. We might want to rethink some concepts and also introduce abstractions (for example for job collections?), but I suggest we keep this task specific task about the clarifications only, to avoid it getting too large :)
