### ISSUE TITLE
Some issues with saving deployments

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#400]
Comments from user testing:
- When creating a deployment, the validation error does not tell you which fields need to be filled in (just shows a 400 error)
- Need to "Save" deployment to update cached values, but can’t save without changing a field (so we currently add a period, etc. to the Description field)
- Manual captures doesn't update cached values (or regroup sessions) when done

**Comment by annavik** [comment]
Some thoughts:
- The first problem is possibly related to the wizard layout. If an error occurs in a form step that is currently not active, this is not visible to the user, which is not optimal. My suggestion would probably be to save each step individually, but let's discuss.
- The second problem I think we should fix by never have the save button disabled (also see #398). But I'm also curious about the cached values, can you explain what happened here @mihow ?

**Comment by mihow** [comment]
@annavik Thanks for defining this one. the cached values are updated whenever the Deployment is saved. So if the user can click Save then they will be updated. The problem has been with the image uploader. I don't want to update the cache on every image upload if the user uploads multiple. It would be nice to auto-save after a batch is uploaded. But also the user can just click Save to update the cache before closing the modal. Can we prevent the modal from being closed or show a warning if anything has been changed? Including manually uploaded captures?

**Comment by mihow** [comment]
The Deployment cache is now updating correctly after #379. I will close and we can revisit any UI issues related to validation later on non-visible wizard tabs if they come up again.
