### ISSUE TITLE
Strange job details

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#404]
After processing one capture, the job details I got in response looked a bit strange... I would expected "Processed" to have value 1 instead of 4 and "Remaining" to have value 0 instead of -3. Is this a bug or am I misunderstanding something @mihow? Here is the request for this example: https://api.beluga.insectai.org/api/v2/jobs/739/

<img width="616" alt="Skärmavbild 2024-06-10 kl  10 46 32" src="https://github.com/RolnickLab/ami-platform/assets/11680517/22428c2d-1497-4d4d-8bc5-1666c8ab0204">

**Comment by mihow** [comment]
Glad you encountered this @annavik. I have seen it to and will fix it in #310
