### ISSUE TITLE
Some UI label inconsistency

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#406]
I have noticed some small inconsistencies for field labels in the interface:
- Sometimes we use "Sentence case", sometimes we use "Title Case".
- For not defined values, sometimes we use "N/A", sometimes empty string.

Just for a bit more polished look, I suggest we choose one strategy here and stick to it.

**Comment by annavik** [comment]
Any thoughts @mihow? I think I would go for "Sentence case" and "N/A", but I mostly I just want it to look streamlined :)

**Comment by mihow** [comment]
I agree with Sentence case! And "N/A" is good, although I could also see an icon if we have one :)
