### ISSUE TITLE
Create public Home/About page

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#415]

**Comment by annavik** [comment]
I think major work here is to define the content. The page itself can be quickly setup, either using the modal we have or as a separate page.

**Comment by joseepoirier** [comment]
@annavik Over to you for visual exploration!

**Comment by mihow** [comment]
@joseepoirier can you link or paste the relevant documents & discussion here that has been created so far?

**Comment by annavik** [comment]
### Update 14/8

- We have some initial content defined, see [Google doc](https://docs.google.com/document/d/1Uxw-1s-jaBCQxXdRa-hxTUxefHj_va9SBROgpogadD0/edit?usp=sharing).
- We have a setup for the layout, see [new repo](https://github.com/RolnickLab/adp-landing-page).

**Next steps:**
- Replace placeholder images with clips/images. 
- Make the site public somewhere, so we can more easily test it out.
- Feedback session in the small team where we go through both content and layout.

**Polish for later:**
- Adjust layout for mobile, let's do this once content and widgets are set to us save time.
- Add some animations. Nothing extreme, but small subtle effects could be nice for a landing page? I'm thinking numbers counting up for stats, some elements sliding in when in view, hover effects, etc.
