### ISSUE TITLE
Small backend issues related to plots

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#445]
Fixed some plot feedback from Lars in #441. There are some small things left which requires backend changes:
- Detections per hour chart is a bit strange 
- Restrict number of species if many in top species chart
- Hover label is sometimes a bit repetitive, for example in top species chart

For the hover label, I have made it possible to specify this from backend since the label might vary depending on what chart we are dealing with. Just pass a `hovertemplate` string: https://plotly.com/javascript/hover-text-and-formatting/#hovertemplate

**Comment by vanessavmac** [comment]
Hi @annavik ! I'm Vanessa, the new backend/MLOps developer intern. Michael assigned this issue to me as a good first issue to get familiar with the code base.

> Detections per hour chart is a bit strange

Would you be able to clarify what issues there are with the detections per hour chart? One thing I noticed is that when I slide the x-axis, sometimes the bars get distorted or turn into weird shapes. Not sure if this is what you were referring to or if there are other changes I should make.

![image](https://github.com/user-attachments/assets/8e7768ce-12dc-4c63-82a4-1ec192eff232)

[445-small-backend-issues-related-to-plots](https://github.com/RolnickLab/ami-platform/tree/445-small-backend-issues-related-to-plots) -- So far, I've addressed the 2 other points you mentioned on this branch.
