### ISSUE TITLE
Deployments with no images show Dec 1969 for the start & end date

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#461]
The API should return NULL for start & end date and the frontend should show nothing (blank, our default NA constant, or a dash). 

![image](https://github.com/user-attachments/assets/2d015b9c-5eab-47ee-97d2-63969c71f601)

**Comment by mihow** [comment]
Hi @anirudh1117, yes that would be fantastic.

**Comment by annavik** [comment]
Fixed in #481
