### ISSUE TITLE
Finalize and add logo

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#468]
We need to add logos of supporting organizations and citation information. There could go in the about modal & home page in the current layout.

**Comment by annavik** [comment]
@joseepoirier can you help define this?

**Comment by joseepoirier** [comment]
This has been approved: 
https://docs.google.com/document/d/1Uxw-1s-jaBCQxXdRa-hxTUxefHj_va9SBROgpogadD0/edit#bookmark=id.8e7zu3te6770
