### ISSUE TITLE
Test README & initial project setup

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#533]
Provide feedback and elaborate on README as you go.

**Comment by mihow** [comment]
Issue with the frontend container!

**Comment by vanessavmac** [comment]
We mentioned during the meeting that we wanted the backend api to automatically redirect to api/v2 (not the home page). I added the simple change to [533-test-readme-initial-project-setup](https://github.com/RolnickLab/ami-platform/tree/533-test-readme-initial-project-setup), but let me know if I should make a separate issue/pull request.

README was clear and easy to follow. One minor change is to specify the node version.

@mihow What node version does the project require? I found node v18.20.4 works, but just want to check.

**Comment by mihow** [comment]
Thank you @vanessavmac! Were you able to create a user locally?

**Comment by vanessavmac** [comment]
Yes, I signed up with a new account and logged in

**Comment by mihow** [comment]
Thanks for make the changes in a branch! Will you make a Pull Request with those? Then I can add a couple comments. You can make the /api/v2 string a variable since that is used a couple places in that urls file now. And delete the 2 lines for /home and /about pages. Those came with the original template and we don't need them since it's an API-only frontend.

**Comment by mihow** [comment]
@vanessavmac the node version is specified in the `.nvmrc` file. If you run `nvm install` and `nvm use` then Node Version Manager will use the version in that file.

Also, I fixed the dependency issue in #554. Will you pull and test `docker compose up` again and see if the ui runs from there? Thanks!

Some other helpful commands:

Rebuild just the UI container:
`docker compose build ui`

Test just the UI container:
`docker compose up ui`

**Comment by vanessavmac** [comment]
@mihow I tried building the UI container and got the same error:

![Screenshot 2024-09-05 at 2 01 38 PM](https://github.com/user-attachments/assets/492c2e48-7e2b-4349-87db-154b9517b083)
