### ISSUE TITLE
Column selection in Occurrences view does not save

### ISSUE THREAD

**Issue by joseepoirier** [RolnickLab/ami-platform#541]
When selecting columns in the Occurrences View, the selection is lost if you navigate away from the page.

**Comment by annavik** [comment]
I'll take this over since I believe we are going for a FE only solution here?

**Comment by mihow** [comment]
That makes sense. I think we could start building a user preferences object on the frontend for all of the user preferences during a browser session, and then persist that entire object in the database. So make it available to read & write from via the /me endpoint. Thoughts?

**Comment by mihow** [comment]
Another option for this one specifically is to save the column selections into URL params. So when you share a link the receiver sees the same columns you are seeing. Or both?

**Comment by annavik** [comment]
That's a great idea @mihow, I fixed this and reworked the structure of all preferences in #544. In that PR we now use one single object for all preferences. When we are ready to sync these preferences to backend, we can do that from one place in code.

To share column preferences as part of URL params I feel could get a bit more messy...? Would those params override any preferences the user already has? I suggest we keep it simple for now, until we see a need for this, what do you think? :)

**Comment by mihow** [comment]
Closed in https://github.com/RolnickLab/ami-platform/pull/544
