### ISSUE TITLE
Solution for wide tables

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#95]
It's awesome that the table is usable with horizontal scrolling, but the page still _appears_ like something is a little wrong. I wonder if there is a visual queue we can add to the right side the table, indicating that it is "supposed" to be cut-off and you can scroll to the right. A little glow/shadow? or tiny arrow?

Or, maybe simpler: What if the right border is always visible, and there is always a little padding on the right side of the window, so the horizontal scrolling happens inside the table element only. Does that make sense? Something like this:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/158175/227030333-d41cc37c-bcf3-4421-a34d-81ea15afe5a3.png">

Also here is an interesting idea for narrow table views, where each row becomes a stacked box with the details listed vertically. I don't know if it will work for us, but it's nice for this simple table example.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/158175/227030513-3b452106-c166-47e4-8314-077f2e8baa1a.png">

More ideas for responsive tables at this site!
https://www.uvm.edu/drupalwebguide/creating-responsive-html-tables

**Comment by annavik** [comment]
Fixed and released!
